version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3100:3100"
    volumes:
      - .:/myapp
    depends_on:
      - mongo
      - redis
    environment:
      RAILS_ENV: development
      DATABASE_URL: mongodb://mongo/myapp_development
      REDIS_URL: redis://redis:6379/0

  mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongodbdata:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

  redis:
    image: redis:6.2
    ports:
      - "6379:6379"

volumes:
  mongodbdata:
